[package]
name = "bign256"
version = "0.13.0"
description = """
Pure Rust implementation of the Bign P-256 (a.k.a. bign-curve256v1)
elliptic curve as defined in STB 34.101.45-2013, with
general purpose curve arithmetic
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/bign256"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/bign256"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "stb", "bign-curve256v1", "bignp256"]
edition = "2021"
rust-version = "1.65"

[dependencies]
elliptic-curve = { version = "0.13.6", features = ["hazmat", "sec1"] }

# optional dependencies
primeorder = { version = "0.13.1", optional = true, path = "../primeorder" }

[dev-dependencies]
criterion = "0.5"
hex-literal = "0.4"
proptest = "1"

[features]
default = ["arithmetic", "pkcs8", "std"]
alloc = ["elliptic-curve/alloc"]
std = ["alloc", "elliptic-curve/std"]

arithmetic = ["dep:primeorder", "elliptic-curve/arithmetic"]
pkcs8 = ["elliptic-curve/pkcs8"]

[[bench]]
name = "field"
harness = false

[[bench]]
name = "scalar"
harness = false
